services:
  - docker
branches:
  only:
    - master
    - deploy
script:
  - eval "$(ssh-agent -s)"
  - ssh-keyscan -H 95.163.209.195 >> ~/.ssh/known_hosts
  - chmod 600 $HOME/.ssh/2019_2_CoolCode_id_rsa.pem
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - cd ./messages
  - docker build -t slack-messages .
  - docker tag -t slack-messages $DOCKER_USER/messages
  - docker push $DOCKER_USER/messages
  - cd ..
  - ssh -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem sudo docker pull $DOCKER_USER/messages
  - ssh -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem sudo docker stop slack-messages || true
  - ssh -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem sudo docker rm slack-messages || true
  - ssh -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem sudo docker run --network=host --name=slack-messages $DOCKER_USER/messages



before_install:
  - openssl aes-256-cbc -K $encrypted_558de5f2c85d_key -iv $encrypted_558de5f2c85d_iv
    -in 2019_2_CoolCode_id_rsa.pem.enc -out $HOME/.ssh/2019_2_CoolCode_id_rsa.pem -d


#  - ssh -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem ubuntu@95.163.209.195 touch /home/ubuntu/test/test.flex
#    fuser -n tcp -k 8002 ; go run /home/ubuntu/Golang/src/github.com/CoolCodeTeam/2019_2_CoolCodeMicroServices/bin/chats & ;
#    fuser -n tcp -k 8003 ; go run /home/ubuntu/Golang/src/github.com/CoolCodeTeam/2019_2_CoolCodeMicroServices/bin/notifications & ;
#    fuser -n tcp -k 8004 ; go run /home/ubuntu/Golang/src/github.com/CoolCodeTeam/2019_2_CoolCodeMicroServices/bin/messages &'