language: go
go:
  - 1.13.x
branches:
  only:
    - master
script:
  - make
  - eval "$(ssh-agent -s)"
  - ssh-keyscan -H 95.163.209.195 >> ~/.ssh/known_hosts
  - chmod 600 $HOME/.ssh/2019_2_CoolCode_id_rsa.pem
  - scp -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem -r ./bin/* ubuntu@95.163.209.195:/home/ubuntu/Golang/src/github.com/CoolCodeTeam/2019_2_CoolCodeMicroServices/bin
  - ssh -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem ubuntu@95.163.209.195 'fuser -n tcp -k 8001'
  - ssh -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem ubuntu@95.163.209.195 '$GOPATH/src/github.com/CoolCodeTeam/2019_2_CoolCodeMicroServices/bin/users'
#    fuser -n tcp -k 8002 ; go run /home/ubuntu/Golang/src/github.com/CoolCodeTeam/2019_2_CoolCodeMicroServices/bin/chats & ;
#    fuser -n tcp -k 8003 ; go run /home/ubuntu/Golang/src/github.com/CoolCodeTeam/2019_2_CoolCodeMicroServices/bin/notifications & ;
#    fuser -n tcp -k 8004 ; go run /home/ubuntu/Golang/src/github.com/CoolCodeTeam/2019_2_CoolCodeMicroServices/bin/messages &'
before_install:
  - openssl aes-256-cbc -K $encrypted_558de5f2c85d_key -iv $encrypted_558de5f2c85d_iv
    -in 2019_2_CoolCode_id_rsa.pem.enc -out $HOME/.ssh/2019_2_CoolCode_id_rsa.pem -d
