language: go
go:
- 1.13.x
branches:
  only:
  - master
script:
- make
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 95.163.209.195 >> ~/.ssh/known_hosts
- chmod 600 $HOME/.ssh/2019_2_CoolCode_id_rsa.pem
- scp -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem -r ./bin/* ubuntu@95.163.209.195:/home/ubuntu/deploy
# - ssh -i $HOME/.ssh/2019_2_CoolCode_id_rsa.pem ubuntu@95.163.212.32 '/home/ubuntu/deploy/users &'
before_install:
- openssl aes-256-cbc -K $encrypted_558de5f2c85d_key -iv $encrypted_558de5f2c85d_iv
  -in 2019_2_CoolCode_id_rsa.pem.enc -out $HOME/.ssh/2019_2_CoolCode_id_rsa.pem -d
