// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifications.proto

package grpc_utils

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestMessageNotification struct {
	ChatID               uint64   `protobuf:"varint,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMessageNotification) Reset()         { *m = RequestMessageNotification{} }
func (m *RequestMessageNotification) String() string { return proto.CompactTextString(m) }
func (*RequestMessageNotification) ProtoMessage()    {}
func (*RequestMessageNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{0}
}

func (m *RequestMessageNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMessageNotification.Unmarshal(m, b)
}
func (m *RequestMessageNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMessageNotification.Marshal(b, m, deterministic)
}
func (m *RequestMessageNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMessageNotification.Merge(m, src)
}
func (m *RequestMessageNotification) XXX_Size() int {
	return xxx_messageInfo_RequestMessageNotification.Size(m)
}
func (m *RequestMessageNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMessageNotification.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMessageNotification proto.InternalMessageInfo

func (m *RequestMessageNotification) GetChatID() uint64 {
	if m != nil {
		return m.ChatID
	}
	return 0
}

func (m *RequestMessageNotification) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type EmptyNotification struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyNotification) Reset()         { *m = EmptyNotification{} }
func (m *EmptyNotification) String() string { return proto.CompactTextString(m) }
func (*EmptyNotification) ProtoMessage()    {}
func (*EmptyNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{1}
}

func (m *EmptyNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyNotification.Unmarshal(m, b)
}
func (m *EmptyNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyNotification.Marshal(b, m, deterministic)
}
func (m *EmptyNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyNotification.Merge(m, src)
}
func (m *EmptyNotification) XXX_Size() int {
	return xxx_messageInfo_EmptyNotification.Size(m)
}
func (m *EmptyNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyNotification.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyNotification proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RequestMessageNotification)(nil), "grpc_utils.RequestMessageNotification")
	proto.RegisterType((*EmptyNotification)(nil), "grpc_utils.EmptyNotification")
}

func init() { proto.RegisterFile("notifications.proto", fileDescriptor_fbc3de4cce73c76f) }

var fileDescriptor_fbc3de4cce73c76f = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0xcb, 0x2f, 0xc9,
	0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x4a, 0x2f, 0x2a, 0x48, 0x8e, 0x2f, 0x2d, 0xc9, 0xcc, 0x29, 0x56, 0xf2, 0xe3, 0x92, 0x0a,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xf5, 0x43, 0xd2,
	0x20, 0x24, 0xc6, 0xc5, 0x96, 0x9c, 0x91, 0x58, 0xe2, 0xe9, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x12, 0x04, 0xe5, 0x09, 0x49, 0x70, 0xb1, 0xe7, 0x42, 0x94, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0xf0,
	0x04, 0xc1, 0xb8, 0x4a, 0xc2, 0x5c, 0x82, 0xae, 0xb9, 0x05, 0x25, 0x95, 0xc8, 0xc6, 0x18, 0xe5,
	0x70, 0x89, 0x20, 0xf3, 0x8b, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x42, 0xb8, 0xb8,
	0x83, 0x53, 0xf3, 0x52, 0xa0, 0x36, 0x0b, 0xa9, 0xe9, 0x21, 0x1c, 0xa6, 0x87, 0xdb, 0x55, 0x52,
	0xb2, 0xc8, 0xea, 0x30, 0x6c, 0x4b, 0x62, 0x03, 0xfb, 0xd2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xf0, 0x09, 0x3f, 0xd8, 0xfc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationsServiceClient is the client API for NotificationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationsServiceClient interface {
	SendMessage(ctx context.Context, in *RequestMessageNotification, opts ...grpc.CallOption) (*EmptyNotification, error)
}

type notificationsServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotificationsServiceClient(cc *grpc.ClientConn) NotificationsServiceClient {
	return &notificationsServiceClient{cc}
}

func (c *notificationsServiceClient) SendMessage(ctx context.Context, in *RequestMessageNotification, opts ...grpc.CallOption) (*EmptyNotification, error) {
	out := new(EmptyNotification)
	err := c.cc.Invoke(ctx, "/grpc_utils.NotificationsService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationsServiceServer is the server API for NotificationsService service.
type NotificationsServiceServer interface {
	SendMessage(context.Context, *RequestMessageNotification) (*EmptyNotification, error)
}

// UnimplementedNotificationsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationsServiceServer struct {
}

func (*UnimplementedNotificationsServiceServer) SendMessage(ctx context.Context, req *RequestMessageNotification) (*EmptyNotification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterNotificationsServiceServer(s *grpc.Server, srv NotificationsServiceServer) {
	s.RegisterService(&_NotificationsService_serviceDesc, srv)
}

func _NotificationsService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessageNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationsServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_utils.NotificationsService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationsServiceServer).SendMessage(ctx, req.(*RequestMessageNotification))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_utils.NotificationsService",
	HandlerType: (*NotificationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _NotificationsService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifications.proto",
}
